# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"a\n\x04\x44\x61ta\x12\x10\n\x08\x44\x65\x63imal1\x18\x01 \x01(\x01\x12\x10\n\x08\x44\x65\x63imal2\x18\x02 \x01(\x01\x12\x10\n\x08\x44\x65\x63imal3\x18\x03 \x01(\x01\x12\x10\n\x08\x44\x65\x63imal4\x18\x04 \x01(\x01\x12\x11\n\tTimestamp\x18\x05 \x01(\x03\"i\n\x0b\x44\x61taRequest\x12\x17\n\x0fPacketTimestamp\x18\x01 \x01(\x03\x12\x14\n\x0cPacketSeqNum\x18\x02 \x01(\x03\x12\x10\n\x08NRecords\x18\x03 \x01(\x05\x12\x19\n\nPacketData\x18\x04 \x03(\x0b\x32\x05.Data\"3\n\x0fServiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2=\n\rPacketService\x12,\n\nPacketData\x12\x0c.DataRequest\x1a\x10.ServiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=17
  _globals['_DATA']._serialized_end=114
  _globals['_DATAREQUEST']._serialized_start=116
  _globals['_DATAREQUEST']._serialized_end=221
  _globals['_SERVICERESPONSE']._serialized_start=223
  _globals['_SERVICERESPONSE']._serialized_end=274
  _globals['_PACKETSERVICE']._serialized_start=276
  _globals['_PACKETSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
